<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[---DataBase connection Successfull---]]>
    </line>
  </reporter-output>
  <suite started-at="2024-06-13T13:31:33 IST" name="Default suite" finished-at="2024-06-13T13:32:09 IST" duration-ms="35867">
    <groups>
    </groups>
    <test started-at="2024-06-13T13:31:33 IST" name="Default test" finished-at="2024-06-13T13:32:09 IST" duration-ms="35867">
      <class name="testNg.ToCreateContactTest">
        <test-method is-config="true" signature="basicConfiguration()[pri:0, instance:testNg.ToCreateContactTest@16eb3ea3]" started-at="2024-06-13T13:31:33 IST" name="basicConfiguration" finished-at="2024-06-13T13:31:33 IST" duration-ms="15" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[---DataBase connection Successfull---]]>
            </line>
          </reporter-output>
        </test-method> <!-- basicConfiguration -->
        <test-method is-config="true" signature="beforeClassConfiguration()[pri:0, instance:testNg.ToCreateContactTest@16eb3ea3]" started-at="2024-06-13T13:31:33 IST" name="beforeClassConfiguration" finished-at="2024-06-13T13:31:43 IST" duration-ms="9516" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClassConfiguration -->
        <test-method is-config="true" signature="beforeMethodConfiguration()[pri:0, instance:testNg.ToCreateContactTest@16eb3ea3]" started-at="2024-06-13T13:31:43 IST" name="beforeMethodConfiguration" finished-at="2024-06-13T13:31:49 IST" duration-ms="6532" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethodConfiguration -->
        <test-method signature="createOrganization()[pri:0, instance:testNg.ToCreateContactTest@16eb3ea3]" started-at="2024-06-13T13:31:49 IST" name="createOrganization" finished-at="2024-06-13T13:32:07 IST" duration-ms="17526" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at testNg.ToCreateContactTest.createOrganization(ToCreateContactTest.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createOrganization -->
        <test-method is-config="true" signature="afterMethodConfiguration()[pri:0, instance:testNg.ToCreateContactTest@16eb3ea3]" started-at="2024-06-13T13:32:07 IST" name="afterMethodConfiguration" finished-at="2024-06-13T13:32:09 IST" duration-ms="1481" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethodConfiguration -->
        <test-method is-config="true" signature="afterClassConfiguration()[pri:0, instance:testNg.ToCreateContactTest@16eb3ea3]" started-at="2024-06-13T13:32:09 IST" name="afterClassConfiguration" finished-at="2024-06-13T13:32:09 IST" duration-ms="196" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClassConfiguration -->
      </class> <!-- testNg.ToCreateContactTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
